### ISSUE TITLE
Merge with ToggleTrafficLights

### ISSUE THREAD

**Issue by cbluoss** [crispies/LaneChanger#1]
Might be worth too merge this one with ToggleTrafficLights (https://github.com/Craxy/ToggleTrafficLights), although it enhances traffic flow way too much through superior gap finding right now.

**Comment by elboletaire** [comment]
:+1: I think it's a very good idea.

**Comment by crispies** [comment]
Current release should no longer conflict with ToggleTrafficLights.  Worked well together in my test city, plan on playing around with it more today.
